name: Build Docker Image
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building Docker Image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          # 下方的name格式为：Docker Hub ID/自定义镜像名称
          name: '${{ secrets.DOCKER_NAME }}'
          username: '${{ secrets.DOCKER_USERNAME }}'
          password: '${{ secrets.DOCKER_PASSWORD }}'
